// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABcb2BRNfUAZOrLUSqfyuWaSrm2d7YSc',
    appId: '1:979890909808:web:9ab92eb8c6c1212ca13ab5',
    messagingSenderId: '979890909808',
    projectId: 'e-shop-assignment-a680e',
    authDomain: 'e-shop-assignment-a680e.firebaseapp.com',
    storageBucket: 'e-shop-assignment-a680e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC36vx8BQvPliqZdPvgjTV9CwyyT27dblU',
    appId: '1:979890909808:android:fb1a3dc208d31adea13ab5',
    messagingSenderId: '979890909808',
    projectId: 'e-shop-assignment-a680e',
    storageBucket: 'e-shop-assignment-a680e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgcw5atDR2X0ccFYNHfytQM5J1vB0lGbs',
    appId: '1:979890909808:ios:270ae619b002070aa13ab5',
    messagingSenderId: '979890909808',
    projectId: 'e-shop-assignment-a680e',
    storageBucket: 'e-shop-assignment-a680e.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgcw5atDR2X0ccFYNHfytQM5J1vB0lGbs',
    appId: '1:979890909808:ios:270ae619b002070aa13ab5',
    messagingSenderId: '979890909808',
    projectId: 'e-shop-assignment-a680e',
    storageBucket: 'e-shop-assignment-a680e.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDABcb2BRNfUAZOrLUSqfyuWaSrm2d7YSc',
    appId: '1:979890909808:web:dfb2a5c0d8182fdda13ab5',
    messagingSenderId: '979890909808',
    projectId: 'e-shop-assignment-a680e',
    authDomain: 'e-shop-assignment-a680e.firebaseapp.com',
    storageBucket: 'e-shop-assignment-a680e.appspot.com',
  );
}
